# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    
    jobs :
      - job: BuildJob

        steps:
          - task: UseNode@1
            inputs:
              version: '20.x'
          
          - script: |
              node --version
              npm --version

          - script: |
              npm ci

          - script: |
              npx prisma validate

          - script: |
              npm run build
          
          - script: |
              ls -la dist
          
